name: 'MSVC ready reusable action made by Lohk'
description: 'Made to build Microsoft Visual Studio projects with MSVC, nuget and submodules as easy as possible.'
inputs:
  build_configuration:
    description: 'Release or Debug?'
    required: false
    default: 'Release'
  checkout:
    description: 'Should this checkout the project automagically?'
    required: false
    default: 'false'
  project_path:
    description: 'Project path to work on?'
    required: false
    default: ${{ runner.workspace }}
  artifact_name:
    description: 'How to name this project outputs as Artifacts?'
    required: true
  
runs:
  using: composite
  steps:
    - name: Put title for summary
      shell: bash
      run: |
        echo "## 🌝 LunarisLib/actions/MSVC" >> $GITHUB_STEP_SUMMARY

        echo "*This is the log output for this action:*" >> $GITHUB_STEP_SUMMARY
        echo "- Kind of build: ${{ inputs.build_configuration }}" >> $GITHUB_STEP_SUMMARY
        echo "- Project path: ${{ inputs.project_path }}" >> $GITHUB_STEP_SUMMARY
        echo "- Artifact name: ${{ inputs.artifact_name }}" >> $GITHUB_STEP_SUMMARY

    - name: Checkout if requested
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@main
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Run NuGet restore and Build
      working-directory: ${{ inputs.project_path }}
      shell: powershell
      run: |
        nuget restore .
        msbuild /m /p:OutDir=${{ runner.workspace }}\build_out\ /p:Configuration=${{ inputs.build_configuration }} .

    - name: Save build folder as artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ runner.workspace }}/build_out/*.exe
        
        
    - name: Finish summary with happy ending
      if: success()
      shell: bash
      run: |
        echo "#### The run ended with no issues ;P" >> $GITHUB_STEP_SUMMARY
    - name: Log errors if no success instead
      if: failure()
      shell: bash
      run: |
        echo "### The run ended with issues! Check the log!" >> $GITHUB_STEP_SUMMARY
        