name: 'MSVC ready reusable action made by Lohk'
description: 'Made to build Microsoft Visual Studio projects with MSVC, nuget and submodules as easy as possible.'
inputs:
  build_configuration:
    description: 'Release or Debug?'
    required: false
    default: 'Release'
  checkout:
    description: 'Should this checkout the project automagically?'
    required: false
    default: 'false'
  project_path:
    description: 'Project path to work on?'
    required: false
    default: ${{ runner.workspace }}
  
runs:
  using: composite
  steps:
    - name: Checkout if requested
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@main
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Run NuGet restore and Build
      working-directory: ${{ inputs.project_path }}
      shell: powershell
      run: |
        nuget restore .
        msbuild /m /p:OutDir=${{ runner.workspace }}\build_out\ /p:Configuration=${{ inputs.build_configuration }} .

    - name: Save build folder as artifact
      uses: actions/upload-artifact@main
      with:
        name: build
        path: ${{ runner.workspace }}/build_out/*.exe
        