name: 'Publisher helper that creates a changelog to append automatically'
description: 'Works on any platform.'
inputs:
  title:
    description: 'Title for the Release page'
    required: true
  body:
    description: 'Text to be on top of the description body'
    required: false
  artifact_name:
    description: 'Files to get from artifacts, or empty if all possible'
    required: false
  tag_name:
    description: 'Tag to be used'
    required: false
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Re-checkout with depth
      uses: actions/checkout@main
      with:
        fetch-depth: 2

    - name: Generate changelog
      shell: bash
      run: |
        printf "${{ inputs.body }}" >> changelog.txt
        if [[ -n "${{ inputs.body }}" ]]; then printf "\n\n" >> changelog.txt; fi
        echo "**Full Changelog**: https://github.com/Lohkdesgds/ImageViewer/compare/$(git rev-parse HEAD~1)...$(git rev-parse HEAD)" >> changelog.txt
            
    - if: ${{ inputs.artifact_name }}
      name: "Download back file"
      uses: actions/download-artifact@master
      with:
        name: ${{ inputs.artifact_name }}
        path: ./.publish_files/

    - if: ${{ ! inputs.artifact_name }}
      name: "Download back all files"
      uses: actions/download-artifact@master
      with:
        path: ./.publish_files/

    - name: Upload
      uses: softprops/action-gh-release@master
      with:
        name: ${{ inputs.title }}
        body_path: changelog.txt
        tag_name: ${{ inputs.tag_name }}
        files: .publish_files/*