name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  build:
    #continue-on-error: true
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:  
      - name: Build
        uses: LunarisLib/actions/CMake@master
        with:
          checkout: 'true'
          project_path: ./.examples/CMake_project/
          artifact_name: ${{ matrix.os }}_PROJECT
          
      - name: Versioning
        id: versioning
        uses: LunarisLib/actions/Versioning@master
        with:
          kind: 'm'
          project: CMAKE_${{ matrix.os }}_PROJECT

      - name: Publish
        uses: LunarisLib/actions/Publisher@master
        with:
          title: "CMake Release"
          body: "This is a sample of a body to the example of a CMake project"
          artifact_names: ${{ matrix.os }}_PROJECT
          tag_name: ${{ steps.versioning.outputs.version }}_${{ matrix.os }}


    