name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  build:
    #continue-on-error: true
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:  
      - name: Build
        uses: LunarisLib/actions/CMake@master
        with:
          checkout: 'true'
          project_path: ./Examples/CMake_project/
          artifact_name: ${{ matrix.os }}_PROJECT


    