on:
  pull_request:
    branches:
      - master

      
jobs:
  cmake-build:
    strategy:
      matrix:
        config:
        - { os: windows-latest, mingw: 'false', name: Windows_MSVC }
        - { os: windows-latest, mingw: 'true',  name: Windows_MinGW }
        - { os: ubuntu-latest,  mingw: 'false', name: Ubuntu }
        - { os: macos-latest,   mingw: 'false', name: MacOS }
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Build CMake
        uses: ./CMake
        with:
          checkout: 'false'
          project_path: ./.examples/CMake_project/
          artifact_name: ${{ matrix.config.name }}_CMAKE_PROJECT
          use_mingw: ${{ matrix.config.mingw }}

  msvc-build:
    name: Native_Windows_MSVC
    runs-on: windows-latest    
    steps:  
      - uses: actions/checkout@v4

      - name: Build
        uses: ./MSVC
        with:
          checkout: 'false'
          project_path: ./.examples/VisualStudio_project/
          artifact_name: MSVC_PROJECT
  
  publish-snapshot-test:
    name: Publish_test
    runs-on: ubuntu-latest
    needs: [ cmake-build, msvc-build ]
    steps:
      - uses: actions/checkout@v4

      - name: Versioning
        id: versioning
        uses: ./Versioning
        with:
          kind: 'snapshot'
          project: PULL_REQUEST_SNAPSHOT_COUNTER

      - name: Publish
        uses: ./Publisher
        with:
          title: "Pull request tester"
          body: "This is triggered on a pull request to check if everything is good."
          tag_name: ${{ steps.versioning.outputs.version }}
          prerelease: 'true'
