name: Visual Studio action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:  
      - name: Build
        uses: LunarisLib/actions/MSVC@master
        with:
          checkout: 'true'
          project_path: ./Examples/VisualStudio_project/


    