name: Visual Studio action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:  
      - name: Build
        uses: LunarisLib/actions/MSVC@master
        with:
          checkout: 'true'
          project_path: ./.examples/VisualStudio_project/
          artifact_name: VS_PROJECT
          
      - name: Versioning
        id: versioning
        uses: LunarisLib/actions/Versioning@master
        with:
          kind: 'm'
          project: VS_PROJECT

      - name: Publish
        uses: LunarisLib/actions/Publisher@master
        with:
          title: "Visual Studio Release"
          body: "This is a sample of a body to the example of a Visual Studio project"
          artifact_name: VS_PROJECT
          tag_name: ${{ steps.versioning.outputs.version }}_Windows


    